# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:categories/:title
relative_permalinks: true

# Setup
title:               Panos' Blog
tagline:             '天道酬勤'
description:         "这是Panos的个人Blog,这里记录了Panos的代码之路,生活所想..."
url:                 http://blog.pengpai.info
baseurl:             /
archiveurl:          /archive.html
feedurl:             /atom.xml
tagsurl:             /tags.html
abouturl:            /about.html
paginate:            8

# About/contact
author:
  name:              Panos
  email:             panoshuang@gmail.com

# Custom vars
version:             1.0.0
